<a href="https://colab.research.google.com/github/Sathyamlai/python/blob/master/class_24_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
'''
"id","name","age","wgt","hgt","chol"
101,aaa,25,50,6.0,60
102,bbb,30,55,5.9,62
103,ccc,24,60,5.9,59
104,ddd,27,80,5.5,80
105,eee,34,90,5.7,85
106,fff,30,56,6.0,60
'''

'\n"id","name","age","wgt","hgt","chol"\n101,aaa,25,50,6.0,60\n102,bbb,30,55,5.9,62\n103,ccc,24,60,5.9,59\n104,ddd,27,80,5.5,80\n105,eee,34,90,5.7,85\n106,fff,30,56,6.0,60\n'

In [2]:
from google.colab import files
uploaded = files.upload()

Saving class24_25_patient.txt to class24_25_patient.txt


In [15]:
f=open('class24_25_patient.txt')
h=f.readline()
lines=f.readlines()

print(lines)

['101,aaa,25,50,6.0,60\n', '102,bbb,30,55,5.9,62\n', '103,ccc,24,60,5.9,59\n', '104,ddd,27,80,5.5,80\n', '105,eee,34,90,5.7,85\n', '106,fff,30,56,6.0,60']


In [18]:
x=[]
y=[]
for line in lines:
  w=line.strip().split(",")
  i=w[2:-1]
  inputs = [float(v) for v in i ]
  x.append(inputs)
  y.append(float(w[-1]))
print(x)
print('***')
print(y)

[[25.0, 50.0, 6.0], [30.0, 55.0, 5.9], [24.0, 60.0, 5.9], [27.0, 80.0, 5.5], [34.0, 90.0, 5.7], [30.0, 56.0, 6.0]]
***
[60.0, 62.0, 59.0, 80.0, 85.0, 60.0]


In [28]:
x=np.array(x)
y=np.array(y)
x.shape
X = np.ones((x.shape[0],x.shape[1]+1))
print(X)
X[:,1:]=x
print(X)
Y=np.c_[y]
print(Y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1.  25.  50.   6. ]
 [ 1.  30.  55.   5.9]
 [ 1.  24.  60.   5.9]
 [ 1.  27.  80.   5.5]
 [ 1.  34.  90.   5.7]
 [ 1.  30.  56.   6. ]]
[[60.]
 [62.]
 [59.]
 [80.]
 [85.]
 [60.]]


In [0]:
#create the polynomial generic function which accepts the input matrix and convert into it's nth degree polynomial
def polynomy(x,n):
  M=np.zeros((x.shape[0],x.shape[1]*n))

  c=0

  for i in range(x.shape[1]):
    col=x[:,i]
    cm=[]
    for j in range(n):
      cm.append(col**(j+1))
    cm=np.array(cm).T
    M[:,c:c+n]=cm
    c+=n
  X=np.ones((M.shape[0],M.shape[1]+1))
  X[:,1:] = M
  return X

In [34]:
polynomy(x,1)

array([[ 1. , 25. , 50. ,  6. ],
       [ 1. , 30. , 55. ,  5.9],
       [ 1. , 24. , 60. ,  5.9],
       [ 1. , 27. , 80. ,  5.5],
       [ 1. , 34. , 90. ,  5.7],
       [ 1. , 30. , 56. ,  6. ]])

In [35]:
polynomy(x,2)

array([[1.000e+00, 2.500e+01, 6.250e+02, 5.000e+01, 2.500e+03, 6.000e+00,
        3.600e+01],
       [1.000e+00, 3.000e+01, 9.000e+02, 5.500e+01, 3.025e+03, 5.900e+00,
        3.481e+01],
       [1.000e+00, 2.400e+01, 5.760e+02, 6.000e+01, 3.600e+03, 5.900e+00,
        3.481e+01],
       [1.000e+00, 2.700e+01, 7.290e+02, 8.000e+01, 6.400e+03, 5.500e+00,
        3.025e+01],
       [1.000e+00, 3.400e+01, 1.156e+03, 9.000e+01, 8.100e+03, 5.700e+00,
        3.249e+01],
       [1.000e+00, 3.000e+01, 9.000e+02, 5.600e+01, 3.136e+03, 6.000e+00,
        3.600e+01]])

In [36]:
polynomy(x,3)

array([[1.00000e+00, 2.50000e+01, 6.25000e+02, 1.56250e+04, 5.00000e+01,
        2.50000e+03, 1.25000e+05, 6.00000e+00, 3.60000e+01, 2.16000e+02],
       [1.00000e+00, 3.00000e+01, 9.00000e+02, 2.70000e+04, 5.50000e+01,
        3.02500e+03, 1.66375e+05, 5.90000e+00, 3.48100e+01, 2.05379e+02],
       [1.00000e+00, 2.40000e+01, 5.76000e+02, 1.38240e+04, 6.00000e+01,
        3.60000e+03, 2.16000e+05, 5.90000e+00, 3.48100e+01, 2.05379e+02],
       [1.00000e+00, 2.70000e+01, 7.29000e+02, 1.96830e+04, 8.00000e+01,
        6.40000e+03, 5.12000e+05, 5.50000e+00, 3.02500e+01, 1.66375e+02],
       [1.00000e+00, 3.40000e+01, 1.15600e+03, 3.93040e+04, 9.00000e+01,
        8.10000e+03, 7.29000e+05, 5.70000e+00, 3.24900e+01, 1.85193e+02],
       [1.00000e+00, 3.00000e+01, 9.00000e+02, 2.70000e+04, 5.60000e+01,
        3.13600e+03, 1.75616e+05, 6.00000e+00, 3.60000e+01, 2.16000e+02]])

In [0]:
#deveope a function for extract the coefficients
from numpy.linalg import inv
def coeffs(x,y):
  #formulae inverse(xT.x).(xT.y)
  left=inv(x.T.dot(x))
  right=(x.T.dot(y))
  beta=left.dot(right)
  return beta

In [0]:
#develope a function for prediction
def predict(x,beta):
  ycap=x.dot(beta)
  return ycap

In [0]:
#develop a function to test the accuracy
def accuracy(y,ycap,closeness):
  de=100-closeness
  d=abs(y-ycap)/y*100
  pcnt=d[d<=de].size
  n=y.size
  acc=pcnt/n*100
  return acc

In [0]:
#prepare the input matrix for Linear model, Quadratic model and Cubic model
LX=polynomy(x,1)
QX=polynomy(x,2)
CX=polynomy(x,3)

In [41]:
print(LX)

[[ 1.  25.  50.   6. ]
 [ 1.  30.  55.   5.9]
 [ 1.  24.  60.   5.9]
 [ 1.  27.  80.   5.5]
 [ 1.  34.  90.   5.7]
 [ 1.  30.  56.   6. ]]


In [44]:
print(QX)

[[1.000e+00 2.500e+01 6.250e+02 5.000e+01 2.500e+03 6.000e+00 3.600e+01]
 [1.000e+00 3.000e+01 9.000e+02 5.500e+01 3.025e+03 5.900e+00 3.481e+01]
 [1.000e+00 2.400e+01 5.760e+02 6.000e+01 3.600e+03 5.900e+00 3.481e+01]
 [1.000e+00 2.700e+01 7.290e+02 8.000e+01 6.400e+03 5.500e+00 3.025e+01]
 [1.000e+00 3.400e+01 1.156e+03 9.000e+01 8.100e+03 5.700e+00 3.249e+01]
 [1.000e+00 3.000e+01 9.000e+02 5.600e+01 3.136e+03 6.000e+00 3.600e+01]]


In [45]:
print(CX)

[[1.00000e+00 2.50000e+01 6.25000e+02 1.56250e+04 5.00000e+01 2.50000e+03
  1.25000e+05 6.00000e+00 3.60000e+01 2.16000e+02]
 [1.00000e+00 3.00000e+01 9.00000e+02 2.70000e+04 5.50000e+01 3.02500e+03
  1.66375e+05 5.90000e+00 3.48100e+01 2.05379e+02]
 [1.00000e+00 2.40000e+01 5.76000e+02 1.38240e+04 6.00000e+01 3.60000e+03
  2.16000e+05 5.90000e+00 3.48100e+01 2.05379e+02]
 [1.00000e+00 2.70000e+01 7.29000e+02 1.96830e+04 8.00000e+01 6.40000e+03
  5.12000e+05 5.50000e+00 3.02500e+01 1.66375e+02]
 [1.00000e+00 3.40000e+01 1.15600e+03 3.93040e+04 9.00000e+01 8.10000e+03
  7.29000e+05 5.70000e+00 3.24900e+01 1.85193e+02]
 [1.00000e+00 3.00000e+01 9.00000e+02 2.70000e+04 5.60000e+01 3.13600e+03
  1.75616e+05 6.00000e+00 3.60000e+01 2.16000e+02]]


In [47]:
print(LX.shape)
print(QX.shape)
print(CX.shape)

(6, 4)
(6, 7)
(6, 10)


In [0]:
#next step is to do the predictions
Lbeta = coeffs(LX,y)
Qbeta = coeffs(QX,y)
Cbeta = coeffs(CX,y)

In [66]:
print(Lbeta)
print(Qbeta)
print(Cbeta)

[133.78588633   0.53229209   0.44109935 -18.847852  ]
[-2.24000000e+02  3.05000000e+01 -4.70703125e-01 -2.65234375e+00
  2.31933594e-02 -2.00000000e+01 -5.00000000e-01]
[-6.91200000e+03  2.62500000e+02 -8.21875000e+00  6.73828125e-02
  2.36250000e+02 -3.68359375e+00  1.86920166e-02 -4.00000000e+01
  1.00000000e+00  2.50000000e-01]


In [67]:
#as of now we have X(LX/QX/CX), y and coefficents are ready
#now call the prediction function
Lpred = predict(LX,Lbeta)
Qpred = predict(QX,Qbeta)
Cpred = predict(CX,Cbeta)

print(Lpred)
print(Qpred)
print(Cpred)

[56.06104421 62.81278662 61.82453082 79.78253491 84.15000267 61.36910077]
[31.67675781 56.24319336 25.82546875 67.48242188 87.77746094 53.5703125 ]
[356.65539551 196.37885583 387.19283594 257.48339844  63.19804004
 196.328125  ]


In [68]:
#now we have to call accuracy function to find the accuracy
Lacc = accuracy(y,Lpred,90)
Qacc = accuracy(y,Qpred,90)
Cacc = accuracy(y,Cpred,90)

print("Accuracy by Linear Model:",Lacc)
print("Accuracy by Quadratic Model:",Qacc)
print("Accuracy by Cubic Model:",Cacc)

Accuracy by Linear Model: 100.0
Accuracy by Quadratic Model: 33.33333333333333
Accuracy by Cubic Model: 0.0
