<a href="https://colab.research.google.com/github/Sathyamlai/python/blob/master/class15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
'''
gender.txt
"age","gen","wgt"
12,m,30
11,f,13
11,m,20
13,m,40
15,m,50
19,m,80
19,f,50
20,f,52
21,f,55
23,m,70
24,m,75
'''

In [0]:
from google.colab import files
uploaded = files.upload()

Saving class15_gender.txt to class15_gender.txt


In [0]:
f=open('class15_gender.txt')
h=f.readline()
lines=f.readlines()

In [0]:
lines

['12,m,30\n',
 '11,f,13\n',
 '11,m,20\n',
 '13,m,40\n',
 '15,m,50\n',
 '19,m,80\n',
 '19,f,50\n',
 '20,f,52\n',
 '21,f,55\n',
 '23,m,70\n',
 '24,m,75']

In [0]:
age=[]
gen=[]
wgt=[]
for line in lines:
  w=line.strip().split(",")
  age.append(int(w[0]))
  gen.append(w[1])
  wgt.append(int(w[-1]))

In [0]:
print(age)
print(gen)
print(wgt)

[12, 11, 11, 13, 15, 19, 19, 20, 21, 23, 24]
['m', 'f', 'm', 'm', 'm', 'm', 'f', 'f', 'f', 'm', 'm']
[30, 13, 20, 40, 50, 80, 50, 52, 55, 70, 75]


In [0]:
age=[]
gen=[]
wgt=[]
for line in lines:
  w=line.strip().split(",")
  age.append(int(w[0]))
  gen.append(w[1])
  wgt.append(int(w[-1]))
  #finding the gender probability
  gencnt={}
  for g in gen:
    if gencnt.get(g) == None:
      gencnt[g]=1
    else:
      gencnt[g]+=1

In [0]:
print(gencnt)

{'m': 7, 'f': 4}


In [0]:
age=[]
gen=[]
wgt=[]
for line in lines:
  w=line.strip().split(",")
  age.append(int(w[0]))
  gen.append(w[1])
  wgt.append(int(w[-1]))
  #finding the gender probability
  gencnt={}
  for g in gen:
    if gencnt.get(g) == None:
      gencnt[g]=1
    else:
      gencnt[g]+=1
  #to find the avg probability
  x=[]
  for g in gen:
    x.append(gencnt[g]/len(gen))

In [0]:
print(gen)
print(x)

['m', 'f', 'm', 'm', 'm', 'm', 'f', 'f', 'f', 'm', 'm']
[0.6363636363636364, 0.36363636363636365, 0.6363636363636364, 0.6363636363636364, 0.6363636363636364, 0.6363636363636364, 0.36363636363636365, 0.36363636363636365, 0.36363636363636365, 0.6363636363636364, 0.6363636363636364]


In [0]:
#create the random weights
noise = np.random.random(len(lines))/100000
print(noise)
noise1 = (2*np.random.random(len(lines))/100000)-1
print(noise1)

[7.18282746e-06 6.78706946e-06 7.72305804e-06 7.88428006e-06
 1.48181489e-06 9.60651177e-06 5.61135397e-06 8.50372069e-06
 4.50869329e-06 2.59790515e-06 3.50307132e-09]
[-0.99998781 -0.99999923 -0.99999406 -0.99999202 -0.99999812 -0.99998045
 -0.99999445 -0.99999785 -0.99999821 -0.99999328 -0.9999852 ]


In [0]:
#adding the random noise to the probabilities
x=np.array(x)
a=x+noise

In [0]:
for v in a:
  print(v)

0.6363708191910918
0.3636431507058199
0.6363713594216793
0.6363715206436923
0.636365118178526
0.6363732428754089
0.36364197499033135
0.36364486735705503
0.36364087232965653
0.6363662342687831
0.6363636398667076


In [0]:
#adding the random noise to the probabilities
x=np.array(x)
a1=x+noise1

In [0]:
for v in a1:
  print(v)

-0.3636241695272706
-0.6363628652713138
-0.3636304198095084
-0.3636283839683969
-0.3636344818378975
-0.36361681273229474
-0.6363580887266814
-0.6363614817888705
-0.6363618508649378
-0.36362964245393237
-0.36362156147594493


In [0]:
#now to prepare feature matrix 
ones=np.ones(len(age))

In [0]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
X=np.c_[ones,age,a]
print(X)

[[ 1.         12.          0.63637082]
 [ 1.         11.          0.36364315]
 [ 1.         11.          0.63637136]
 [ 1.         13.          0.63637152]
 [ 1.         15.          0.63636512]
 [ 1.         19.          0.63637324]
 [ 1.         19.          0.36364197]
 [ 1.         20.          0.36364487]
 [ 1.         21.          0.36364087]
 [ 1.         23.          0.63636623]
 [ 1.         24.          0.63636364]]


In [0]:
#Now prepare the label matrix
Y=np.c_[wgt]
print(Y)

[[30]
 [13]
 [20]
 [40]
 [50]
 [80]
 [50]
 [52]
 [55]
 [70]
 [75]]
