<a href="https://colab.research.google.com/github/Sathyamlai/python/blob/master/class_40.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#gradient descent algorithm impl

In [97]:
x=np.arange(5)+1
print(x)
y=np.array([3,7,5,11,14])
print(y)

[1 2 3 4 5]
[ 3  7  5 11 14]


In [98]:
ones=np.ones(len(x))
ones
X=np.c_[ones,x]
print(X)
Y=np.c_[y]
print(Y)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]]
[[ 3]
 [ 7]
 [ 5]
 [11]
 [14]]


In [99]:
beta=np.zeros(X.shape[1])
beta
beta=np.c_[beta]
beta

array([[0.],
       [0.]])

In [0]:
def predict(x,beta):
  ycap=x.dot(beta)
  return ycap

In [0]:
def mse(y,ycap):
  res=((y-ycap)**2).mean()
  return res

In [0]:
def derivative(x,y,beta):
  ycap=predict(x,beta)
  res = (x.T.dot(y-ycap))/y.size
  return res

In [103]:
ycap=predict(X,beta)
#print(ycap)
error1 = mse(Y,ycap)
print("1st iteration Error :", error1)

1st iteration Error : 80.0


In [104]:
delta=derivative(X,Y,beta)
print(delta)

[[ 8. ]
 [29.2]]


In [105]:
beta = beta+0.05*delta
print(beta)

[[0.4 ]
 [1.46]]


In [106]:
ycap=predict(X,beta)
print(ycap)

[[1.86]
 [3.32]
 [4.78]
 [6.24]
 [7.7 ]]


In [107]:
error2 = mse(Y,ycap)
print("2nd iteration Error:", error2)

2nd iteration Error: 15.4476


In [108]:
delta=derivative(X,Y,beta)
print(delta)

[[ 3.22]
 [11.94]]


In [109]:
beta=beta+0.05*delta
print(beta)

[[0.561]
 [2.057]]


In [0]:
ycap=predict(X,beta)

In [111]:
error3 = mse(Y,ycap)
print("3rd iteration error:",error3)

3rd iteration error: 4.677522


In [112]:
print("1st iteration error",error1)
print("2nd iteration error",error2)
print("3rd iteration error",error3)

1st iteration error 80.0
2nd iteration error 15.4476
3rd iteration error 4.677522


In [0]:
def train(x,y,iter,alpha,conv):
  beta=np.zeros(x.shape[1])
  beta=np.c_[beta]
  perr=0
  for i in range(iter):
    ycap = predict(x,beta)
    cerr=mse(y,ycap)

    diff = np.abs(perr-cerr)

    if i%50==0:
      print("current error:", cerr)

    j=0
    if diff <=conv:
      print("Training completed:", i+1 ,"Iterations" )
      j=1
      break
    delta = derivative(x,y,beta)
    beta = beta +alpha*delta
    perr=cerr

  if j==0:
    print("Training not completed")
  return beta

In [122]:
theta=train(X,Y,1000,0.05,0.0000001)

current error: 80.0
current error: 2.498177539540115
current error: 2.48777842441168
current error: 2.4833284970275917
current error: 2.4814243106156626
current error: 2.4806094825121
current error: 2.4802608061250617
current error: 2.4801116026030607
current error: 2.4800477563209316
current error: 2.4800204356003044
current error: 2.480008744680319
Training completed: 525 Iterations
