<a href="https://colab.research.google.com/github/Sathyamlai/python/blob/master/class42.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#1st  apply the scaling for the unscaled Matrix and 
#then apply the gradient to tune the coefficients and 
#then apply the prediction and 
#then apply the accuracy function

In [3]:
from google.colab import files
uploaded = files.upload()

Saving class42_patients.txt to class42_patients.txt


In [9]:
f=open('class42_patients.txt')
h=f.readline()
print(h)
lines=f.readlines()
print(lines)

"id","name","age","wgt","hgt","chol"

['101,aaa,25,50,6.0,60\n', '102,bbb,30,55,5.9,62\n', '103,ccc,24,60,5.9,59\n', '104,ddd,27,80,5.5,80\n', '105,eee,34,90,5.7,85\n', '106,fff,30,56,6.0,60']


In [12]:
age=[]
wgt=[]
hgt=[]
chol=[]
for line in lines:
  w=line.strip().split(",")
  age.append(float(w[2]))
  wgt.append(float(w[3]))
  hgt.append(float(w[4]))
  chol.append(float(w[-1]))
print(age)

[25.0, 30.0, 24.0, 27.0, 34.0, 30.0]


In [17]:
ones=np.ones(len(lines))
print(ones)

[1. 1. 1. 1. 1. 1.]


In [19]:
X=np.c_[ones,age,wgt,hgt]
print(X)

[[ 1.  25.  50.   6. ]
 [ 1.  30.  55.   5.9]
 [ 1.  24.  60.   5.9]
 [ 1.  27.  80.   5.5]
 [ 1.  34.  90.   5.7]
 [ 1.  30.  56.   6. ]]


In [22]:
Y=np.c_[chol]
print(Y)

[[60.]
 [62.]
 [59.]
 [80.]
 [85.]
 [60.]]


In [0]:
#function for standard deviation
def sd(x):
  nr = (x-x.mean())
  nr2 = nr**2
  de = (x.size-1)
  res = (nr2/de)**0.5
  #res = (((x-x.mean())**2)/(x.size-1))**0.5
  return res

def scale(x):
  num = x-x.mean()
  den = sd(x)
  res = num / den
  return res

def scaleMatrix(x):
  ncol = x.shape[1]
  for i in range(ncol):
    if i == 0:
      continue
    c = x[:,i]
    x[:,i] = scale(c)
    return x


In [26]:
age=np.array(age)
wgt=np.array(wgt)
hgt=np.array(hgt)
X = scaleMatrix(X)
Y=scale(Y)

print(X)
print(Y)

[[ 1.         -2.23606798 50.          6.        ]
 [ 1.          2.23606798 55.          5.9       ]
 [ 1.         -2.23606798 60.          5.9       ]
 [ 1.         -2.23606798 80.          5.5       ]
 [ 1.          2.23606798 90.          5.7       ]
 [ 1.          2.23606798 56.          6.        ]]
[[-2.23606798]
 [-2.23606798]
 [-2.23606798]
 [ 2.23606798]
 [ 2.23606798]
 [-2.23606798]]
