<a href="https://colab.research.google.com/github/Sathyamlai/python/blob/master/class13_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
'''
qualifications.txt
"age","exp","qual","income"
23,3,btech,30000
24,3,mtech,35000
33,7,phd,90000
23,3,bsc,30000
23,3,mba,30000
23,3,btech,30000
'''

'\nqualifications.txt\n"age","exp","qual","income"\n23,3,btech,30000\n24,3,mtech,35000\n33,7,phd,90000\n23,3,bsc,30000\n23,3,mba,30000\n23,3,btech,30000\n'

In [0]:
from google.colab import files
uploaded = files.upload()

Saving qualifications.txt to qualifications.txt


In [0]:
f=open('qualifications.txt')
h=f.readline()
lines=f.readlines()

In [0]:
lines

['23,3,btech,30000\n',
 '24,3,mtech,35000\n',
 '33,7,phd,90000\n',
 '23,3,bsc,30000\n',
 '23,3,mba,30000\n',
 '23,3,btech,30000']

In [0]:
age=[]
exp=[]
qual=[]
inc=[]
for line in lines:
  w=line.strip().split(",")
  age.append(int(w[0]))
  exp.append(int(w[1]))
  q=w[2]
  #default score
  qs=3
  if q == 'btech':
    qs=5
  elif q == 'mtech':
    qs=7
  elif q == 'phd':
    qs=9
  qual.append(qs)
  inc.append(float(w[-1]))


In [0]:
print(age)
print(exp)
print(qual)
print(inc)

[23, 24, 33, 23, 23, 23]
[3, 3, 7, 3, 3, 3]
[5, 7, 9, 3, 3, 5]
[30000.0, 35000.0, 90000.0, 30000.0, 30000.0, 30000.0]


In [0]:
ones=np.ones(len(age))

In [0]:
ones

array([1., 1., 1., 1., 1., 1.])

In [0]:
X=np.c_[ones,age,exp,qual]
print(X)

[[ 1. 23.  3.  5.]
 [ 1. 24.  3.  7.]
 [ 1. 33.  7.  9.]
 [ 1. 23.  3.  3.]
 [ 1. 23.  3.  3.]
 [ 1. 23.  3.  5.]]


In [0]:
Y=np.c_[inc]
print(Y)

[[30000.]
 [35000.]
 [90000.]
 [30000.]
 [30000.]
 [30000.]]
