<a href="https://colab.research.google.com/github/Sathyamlai/python/blob/master/class46_WIP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
'''
"name","age","wgt","hgt","diabetic"
aaa,25,60,5.9,yes
bbb,26,67,6.0,no
ccc,45,78,5.5,yes
ddd,56,80,5.9,no
eee,55,81,6.0,no
fff,56,79,5.11,no
ggg,55,79,5.4,yes
hhh,56,89,5.9,yes
iii,49,70,5.6,no
jjj,49,75,5.6,yes
kkk,52,80,5.7,yes
'''

'\n"name","age","wgt","hgt","diabetic"\naaa,25,60,5.9,yes\nbbb,26,67,6.0,no\nccc,45,78,5.5,yes\nddd,56,80,5.9,no\neee,55,81,6.0,no\nfff,56,79,5.11,no\nggg,55,79,5.4,yes\nhhh,56,89,5.9,yes\niii,49,70,5.6,no\njjj,49,75,5.6,yes\nkkk,52,80,5.7,yes\n'

In [2]:
from google.colab import files
uploaded = files.upload()

Saving class46_patients_upd.txt to class46_patients_upd.txt


In [3]:
f=open('class46_patients_upd.txt')
h=f.readline()
lines=f.readlines()
print (h)
print (lines)

"name","age","wgt","hgt","diabetic"

['aaa,25,60,5.9,yes\n', 'bbb,26,67,6.0,no\n', 'ccc,45,78,5.5,yes\n', 'ddd,56,80,5.9,no\n', 'eee,55,81,6.0,no\n', 'fff,56,79,5.11,no\n', 'ggg,55,79,5.4,yes\n', 'hhh,56,89,5.9,yes\n', 'iii,49,70,5.6,no\n', 'jjj,49,75,5.6,yes\n', 'kkk,52,80,5.7,yes']


In [7]:
age=[]
wgt=[]
hgt=[]
dstat=[]
for line in lines:
  w=line.strip().split(",")
  age.append(float(w[1]))
  wgt.append(float(w[2]))
  hgt.append(float(w[3]))
  d=0
  if w[-1] == 'yes':
       d=1
  dstat.append(d)

print(age)
print(wgt)
print(hgt)
print(dstat)

[25.0, 26.0, 45.0, 56.0, 55.0, 56.0, 55.0, 56.0, 49.0, 49.0, 52.0]
[60.0, 67.0, 78.0, 80.0, 81.0, 79.0, 79.0, 89.0, 70.0, 75.0, 80.0]
[5.9, 6.0, 5.5, 5.9, 6.0, 5.11, 5.4, 5.9, 5.6, 5.6, 5.7]
[1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1]


In [8]:
age=np.array(age)
wgt=np.array(wgt)
hgt=np.array(hgt)
dstat=np.array(dstat)

ones=np.ones(len(lines))
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [17]:
X=np.c_[ones,age,wgt,hgt]
print(X)

[[ 1.   25.   60.    5.9 ]
 [ 1.   26.   67.    6.  ]
 [ 1.   45.   78.    5.5 ]
 [ 1.   56.   80.    5.9 ]
 [ 1.   55.   81.    6.  ]
 [ 1.   56.   79.    5.11]
 [ 1.   55.   79.    5.4 ]
 [ 1.   56.   89.    5.9 ]
 [ 1.   49.   70.    5.6 ]
 [ 1.   49.   75.    5.6 ]
 [ 1.   52.   80.    5.7 ]]


In [18]:
Y=np.c_[dstat]
print(Y)

[[1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]]


In [0]:
#function for standard deviation
'''
  #nr = (x#-x.mean())
  #nr2 = (nr**2).sum()
  #de = (x.size#-1)
  #res = (nr2/de)**0.5
'''
def sd(x):
  res = (((x-x.mean())**2).sum()/(x.size-1))**0.5
  return res

def scale(x):
  num = x-x.mean()
  den = sd(x)
  res = num / den
  return res

def scaleMatrix(x):
  ncol = x.shape[1]
  for i in range(ncol):
    if i == 0:
      continue
    c = x[:,i]
    x[:,i] = scale(c)
  return x

In [22]:
print(age)
print(wgt)
print(hgt)
print(dstat)

[25. 26. 45. 56. 55. 56. 55. 56. 49. 49. 52.]
[60. 67. 78. 80. 81. 79. 79. 89. 70. 75. 80.]
[5.9  6.   5.5  5.9  6.   5.11 5.4  5.9  5.6  5.6  5.7 ]
[1 0 1 0 0 0 1 1 0 1 1]


In [30]:
#calculating the mean of age, sd of age and other parameters
ma = sum(age)/len(age)
#sa = sd(age)

mw = sum(wgt)/len(wgt)
#sw = sd(wgt)

mh = sum(hgt)/len(hgt)
#sh = sd(hgt)

md = sum(dstat)/len(dstat)
#sd = sd(dstat)

print("mean of age:",ma)
print("mean of weight:",mw)
print("mean of height:",mh)
print("mean of diabetic status:",md)
print("-------------")
print("sd of age:",sa)
print("sd of weight:",sw)
print("sd of height:",sh)
print("sd of diabetic stat:",sd)

mean of age: 47.63636363636363
mean of weight: 76.18181818181819
mean of height: 5.691818181818181
mean of diabetic status: 0.5454545454545454
-------------
sd of age: 11.526254615205474
sd of weight: 7.884391946347946
sd of height: 0.2823762802297028
sd of diabetic stat: 0.5222329678670935


In [34]:
X = scaleMatrix(X)
Y=scale(Y)

print(X)
print("------")
print(Y)

[[ 1.         -1.96389585 -2.05238632  0.73724967]
 [ 1.         -1.8771374  -1.16455628  1.09138706]
 [ 1.         -0.22872683  0.2306052  -0.67929991]
 [ 1.          0.72561614  0.48427093  0.73724967]
 [ 1.          0.63885769  0.61110379  1.09138706]
 [ 1.          0.72561614  0.35743807 -2.06043575]
 [ 1.          0.63885769  0.35743807 -1.0334373 ]
 [ 1.          0.72561614  1.62576669  0.73724967]
 [ 1.          0.11830698 -0.7840577  -0.32516252]
 [ 1.          0.11830698 -0.14989338 -0.32516252]
 [ 1.          0.37858233  0.48427093  0.02897488]]
------
[[ 0.87038828]
 [-1.04446594]
 [ 0.87038828]
 [-1.04446594]
 [-1.04446594]
 [-1.04446594]
 [ 0.87038828]
 [ 0.87038828]
 [-1.04446594]
 [ 0.87038828]
 [ 0.87038828]]


In [0]:
#apply the gradient 
def predict(x,beta):
  ycap=x.dot(beta)
  return ycap

def mse(y,ycap):
  res=((y-ycap)**2).mean()
  return res

def derivative(x,y,beta):
  ycap=predict(x,beta)
  res = (x.T.dot(y-ycap))/y.size
  return res

def train(x,y,iter,alpha,conv):
  beta=np.zeros(x.shape[1])
  beta=np.c_[beta]
  perr=0
  for i in range(iter):
    ycap = predict(x,beta)
    cerr=mse(y,ycap)

    diff = np.abs(perr-cerr)

    if i%50==0:
      print("current error:", cerr)

    j=0
    if diff <=conv:
      print("Training completed:", i+1 ,"Iterations" )
      j=1
      break
    delta = derivative(x,y,beta)
    beta = beta +alpha*delta
    perr=cerr

  if j==0:
    print("Training not completed")
  return beta

In [37]:
theta=train(X,Y,10000,0.05,0.0000001)

current error: 0.9090909090909091
current error: 0.8489726184854404
current error: 0.8147305932385073
current error: 0.7933861575143009
current error: 0.7800569860004006
current error: 0.7717327953121632
current error: 0.7665342550899701
current error: 0.763287714700337
current error: 0.761260217737837
current error: 0.7599940255949154
current error: 0.7592032759304523
current error: 0.7587094448516983
current error: 0.7584010424010839
current error: 0.7582084419843884
current error: 0.7580881610967453
current error: 0.7580130444787211
current error: 0.7579661333990476
current error: 0.7579368369603369
current error: 0.7579185410411827
current error: 0.7579071150565774
current error: 0.7578999794148479
Training completed: 1014 Iterations


In [38]:
print(theta)

[[ 8.02388459e-17]
 [-8.81682096e-01]
 [ 8.09086007e-01]
 [-3.14872703e-01]]
