<a href="https://colab.research.google.com/github/Sathyamlai/python/blob/master/class16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
'''
patient.txt
"id","name","age","wgt","hgt","chol"
101,aaa,25,50,6.0,60
102,bbb,30,55,5.9,62
103,ccc,24,60,5.9,59
104,ddd,27,80,5.5,80
105,eee,34,90,5.7,85
106,fff,30,56,6.0,60
'''

In [0]:
#standard deviation
def sd(x):
  a=x-x.mean()
  pow=a**2
  numerator=pow.sum()
  den=x.size-1
  res = (numerator/den)**0.5
  return res


In [0]:
#test the sd function
x=[10,20,30]
x=np.array(x)
sd(x)

10.0

In [0]:
def scale2(x):
  num=x-x.mean()
  den=sd(x)
  return num/den

In [0]:
#testing the scale2 function
a=np.array([1,2,3,9,10,11])
scale2(a)

array([-1.11803399, -0.89442719, -0.67082039,  0.67082039,  0.89442719,
        1.11803399])

In [0]:
#build a function which accepts n number of columns to calculate the scale2 feature
def scaleMatrix(M):
  for i in range(M.shape[1]):
    col=M[:,i]
    M[:,i]=scale2(col)
  return M

In [0]:
#test the above scaleMatrix function with 3 columns
v1=[1,2,5,6,9]
v2=[10,100,12,13,90]
v3=[1,99,50,120,3]
a=np.c_[v1,v2,v3]
scaleMatrix(a)
#print(a.shape)

array([[-1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0,  0],
       [ 0,  0,  1],
       [ 1,  0,  0]])

In [0]:
#all the required functions are built, so now read the file and apply the scaling on the data.
from google.colab import files
uploaded = files.upload()

Saving class16_patient.txt to class16_patient.txt


In [0]:
f=open('class16_patient.txt')
h=f.readline()
lines=f.readlines()
lines

['101,aaa,25,50,6.0,60\n',
 '102,bbb,30,55,5.9,62\n',
 '103,ccc,24,60,5.9,59\n',
 '104,ddd,27,80,5.5,80\n',
 '105,eee,34,90,5.7,85\n',
 '106,fff,30,56,6.0,60']

In [0]:
m=[]
for line in lines:
  #w=line.strip().split(",")
  w=[float(v) for v in line.strip().split(",")[2:]]
  m.append(w)

m

[[25.0, 50.0, 6.0, 60.0],
 [30.0, 55.0, 5.9, 62.0],
 [24.0, 60.0, 5.9, 59.0],
 [27.0, 80.0, 5.5, 80.0],
 [34.0, 90.0, 5.7, 85.0],
 [30.0, 56.0, 6.0, 60.0]]

In [0]:
M=np.array(m)
M

array([[25. , 50. ,  6. , 60. ],
       [30. , 55. ,  5.9, 62. ],
       [24. , 60. ,  5.9, 59. ],
       [27. , 80. ,  5.5, 80. ],
       [34. , 90. ,  5.7, 85. ],
       [30. , 56. ,  6. , 60. ]])

In [0]:
scaleMatrix(M)
#as the given input data the problem is regression problem, so we sclaed the label also along with feature

array([[-0.89514359, -0.94760825,  0.84757938, -0.65870409],
       [ 0.4475718 , -0.63520993,  0.33903175, -0.48686824],
       [-1.16368667, -0.3228116 ,  0.33903175, -0.74462201],
       [-0.35805744,  0.9267817 , -1.69515876,  1.0596544 ],
       [ 1.52174411,  1.55157834, -0.6780635 ,  1.48924403],
       [ 0.4475718 , -0.57273026,  0.84757938, -0.65870409]])

In [0]:
#As the this is the regression problem, prepare the feature as ones in first column
ones=np.ones(M.shape)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
#now to keep the age,wgt and hgt in feature matrix as 2nd,3rd and 4th columns
X=ones
X[:,1:]=M[:,0:3]
X

array([[ 1.        , -0.89514359, -0.94760825,  0.84757938],
       [ 1.        ,  0.4475718 , -0.63520993,  0.33903175],
       [ 1.        , -1.16368667, -0.3228116 ,  0.33903175],
       [ 1.        , -0.35805744,  0.9267817 , -1.69515876],
       [ 1.        ,  1.52174411,  1.55157834, -0.6780635 ],
       [ 1.        ,  0.4475718 , -0.57273026,  0.84757938]])

In [0]:
Y=M[:,-1]
Y

array([-0.65870409, -0.48686824, -0.74462201,  1.0596544 ,  1.48924403,
       -0.65870409])

In [0]:
Y=np.c_[M[:,-1]]
Y

array([[-0.65870409],
       [-0.48686824],
       [-0.74462201],
       [ 1.0596544 ],
       [ 1.48924403],
       [-0.65870409]])