<a href="https://colab.research.google.com/github/Sathyamlai/python/blob/master/Copy_of_class42.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#1st  apply the scaling for the unscaled Matrix and 
#then apply the gradient to tune the coefficients and 
#then apply the prediction and 
#then apply the accuracy function

In [8]:
from google.colab import files
uploaded = files.upload()

Saving class42_patients.txt to class42_patients (1).txt


In [9]:
f=open('class42_patients.txt')
h=f.readline()
print(h)
lines=f.readlines()
print(lines)

"id","name","age","wgt","hgt","chol"

['101,aaa,25,50,6.0,60\n', '102,bbb,30,55,5.9,62\n', '103,ccc,24,60,5.9,59\n', '104,ddd,27,80,5.5,80\n', '105,eee,34,90,5.7,85\n', '106,fff,30,56,6.0,60']


In [10]:
age=[]
wgt=[]
hgt=[]
chol=[]
for line in lines:
  w=line.strip().split(",")
  age.append(float(w[2]))
  wgt.append(float(w[3]))
  hgt.append(float(w[4]))
  chol.append(float(w[-1]))
print(age)

[25.0, 30.0, 24.0, 27.0, 34.0, 30.0]


In [13]:
age=np.array(age)
wgt=np.array(wgt)
hgt=np.array(hgt)
chol=np.array(chol)

ones=np.ones(len(lines))
print(ones)

[1. 1. 1. 1. 1. 1.]


In [14]:
X=np.c_[ones,age,wgt,hgt]
print(X)

[[ 1.  25.  50.   6. ]
 [ 1.  30.  55.   5.9]
 [ 1.  24.  60.   5.9]
 [ 1.  27.  80.   5.5]
 [ 1.  34.  90.   5.7]
 [ 1.  30.  56.   6. ]]


In [15]:
Y=np.c_[chol]
print(Y)

[[60.]
 [62.]
 [59.]
 [80.]
 [85.]
 [60.]]


In [0]:
#function for standard deviation
def sd(x):
  #nr = (x-x.mean())
  #nr2 = (nr**2).sum()
  #de = (x.size-1)
  #res = (nr2/de)**0.5
  res = (((x-x.mean())**2).sum()/(x.size-1))**0.5
  return res

def scale(x):
  num = x-x.mean()
  den = sd(x)
  res = num / den
  return res

def scaleMatrix(x):
  ncol = x.shape[1]
  for i in range(ncol):
    if i == 0:
      continue
    c = x[:,i]
    x[:,i] = scale(c)
  return x


In [23]:
X = scaleMatrix(X)
Y=scale(Y)

print(X)
print(Y)

[[ 1.         -0.89514359 -0.94760825  0.84757938]
 [ 1.          0.4475718  -0.63520993  0.33903175]
 [ 1.         -1.16368667 -0.3228116   0.33903175]
 [ 1.         -0.35805744  0.9267817  -1.69515876]
 [ 1.          1.52174411  1.55157834 -0.6780635 ]
 [ 1.          0.4475718  -0.57273026  0.84757938]]
[[-0.65870409]
 [-0.48686824]
 [-0.74462201]
 [ 1.0596544 ]
 [ 1.48924403]
 [-0.65870409]]


In [0]:
def predict(x,beta):
  ycap=x.dot(beta)
  return ycap

def mse(y,ycap):
  res=((y-ycap)**2).mean()
  return res

def derivative(x,y,beta):
  ycap=predict(x,beta)
  res = (x.T.dot(y-ycap))/y.size
  return res

def train(x,y,iter,alpha,conv):
  beta=np.zeros(x.shape[1])
  beta=np.c_[beta]
  perr=0
  for i in range(iter):
    ycap = predict(x,beta)
    cerr=mse(y,ycap)

    diff = np.abs(perr-cerr)

    if i%50==0:
      print("current error:", cerr)

    j=0
    if diff <=conv:
      print("Training completed:", i+1 ,"Iterations" )
      j=1
      break
    delta = derivative(x,y,beta)
    beta = beta +alpha*delta
    perr=cerr

  if j==0:
    print("Training not completed")
  return beta

In [25]:
theta=train(X,Y,1000,0.05,0.0000001)

current error: 0.8333333333333335
current error: 0.03512108442765058
current error: 0.03436318774814893
current error: 0.03396594882005479
current error: 0.033683999931218116
current error: 0.033481951493396465
current error: 0.03333709841064446
current error: 0.03323324796452108
current error: 0.03315879373635013
current error: 0.033105414742674366
current error: 0.033067145365088105
current error: 0.03303970863089544
current error: 0.03302003821996533
current error: 0.03300593577382717
current error: 0.032995825207871664
current error: 0.03298857656866836
Training completed: 782 Iterations


In [26]:
print(theta)

[[ 9.42301792e-16]
 [ 1.74721230e-01]
 [ 5.95543549e-01]
 [-3.27577400e-01]]
