<a href="https://colab.research.google.com/github/Sathyamlai/python/blob/master/Copy_of_class42_43.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#1st  apply the scaling for the unscaled Matrix and 
#then apply the gradient to tune the coefficients and 
#then apply the prediction and 
#then apply the accuracy function

In [22]:
from google.colab import files
uploaded = files.upload()

In [23]:
f=open('class42_patients.txt')
h=f.readline()
print(h)
lines=f.readlines()
print(lines)

"id","name","age","wgt","hgt","chol"

['101,aaa,25,50,6.0,60\n', '102,bbb,30,55,5.9,62\n', '103,ccc,24,60,5.9,59\n', '104,ddd,27,80,5.5,80\n', '105,eee,34,90,5.7,85\n', '106,fff,30,56,6.0,60']


In [24]:
age=[]
wgt=[]
hgt=[]
chol=[]
for line in lines:
  w=line.strip().split(",")
  age.append(float(w[2]))
  wgt.append(float(w[3]))
  hgt.append(float(w[4]))
  chol.append(float(w[-1]))
print(age)

[25.0, 30.0, 24.0, 27.0, 34.0, 30.0]


In [25]:
age=np.array(age)
wgt=np.array(wgt)
hgt=np.array(hgt)
chol=np.array(chol)

ones=np.ones(len(lines))
print(ones)

[1. 1. 1. 1. 1. 1.]


In [0]:
#calculating the mean of age, sd of age and other parameters
ma = sum(age)/len(age)
sa = sd(age)

mw = sum(wgt)/len(wgt)
sw = sd(wgt)

mh = sum(hgt)/len(hgt)
sh = sd(hgt)

mc = sum(chol)/len(chol)
sc = sd(chol)

In [27]:
X=np.c_[ones,age,wgt,hgt]
print(X)

[[ 1.  25.  50.   6. ]
 [ 1.  30.  55.   5.9]
 [ 1.  24.  60.   5.9]
 [ 1.  27.  80.   5.5]
 [ 1.  34.  90.   5.7]
 [ 1.  30.  56.   6. ]]


In [28]:
Y=np.c_[chol]
print(Y)

[[60.]
 [62.]
 [59.]
 [80.]
 [85.]
 [60.]]


In [0]:
#function for standard deviation
def sd(x):
  #nr = (x-x.mean())
  #nr2 = (nr**2).sum()
  #de = (x.size-1)
  #res = (nr2/de)**0.5
  res = (((x-x.mean())**2).sum()/(x.size-1))**0.5
  return res

def scale(x):
  num = x-x.mean()
  den = sd(x)
  res = num / den
  return res

def scaleMatrix(x):
  ncol = x.shape[1]
  for i in range(ncol):
    if i == 0:
      continue
    c = x[:,i]
    x[:,i] = scale(c)
  return x


In [30]:
X = scaleMatrix(X)
Y=scale(Y)

print(X)
print(Y)

[[ 1.         -0.89514359 -0.94760825  0.84757938]
 [ 1.          0.4475718  -0.63520993  0.33903175]
 [ 1.         -1.16368667 -0.3228116   0.33903175]
 [ 1.         -0.35805744  0.9267817  -1.69515876]
 [ 1.          1.52174411  1.55157834 -0.6780635 ]
 [ 1.          0.4475718  -0.57273026  0.84757938]]
[[-0.65870409]
 [-0.48686824]
 [-0.74462201]
 [ 1.0596544 ]
 [ 1.48924403]
 [-0.65870409]]


In [0]:
def predict(x,beta):
  ycap=x.dot(beta)
  return ycap

def mse(y,ycap):
  res=((y-ycap)**2).mean()
  return res

def derivative(x,y,beta):
  ycap=predict(x,beta)
  res = (x.T.dot(y-ycap))/y.size
  return res

def train(x,y,iter,alpha,conv):
  beta=np.zeros(x.shape[1])
  beta=np.c_[beta]
  perr=0
  for i in range(iter):
    ycap = predict(x,beta)
    cerr=mse(y,ycap)

    diff = np.abs(perr-cerr)

    if i%50==0:
      print("current error:", cerr)

    j=0
    if diff <=conv:
      print("Training completed:", i+1 ,"Iterations" )
      j=1
      break
    delta = derivative(x,y,beta)
    beta = beta +alpha*delta
    perr=cerr

  if j==0:
    print("Training not completed")
  return beta

In [32]:
theta=train(X,Y,1000,0.05,0.0000001)

current error: 0.8333333333333336
current error: 0.03512108442765058
current error: 0.03436318774814892
current error: 0.03396594882005478
current error: 0.03368399993121813
current error: 0.033481951493396465
current error: 0.03333709841064445
current error: 0.03323324796452109
current error: 0.03315879373635011
current error: 0.033105414742674394
current error: 0.033067145365088105
current error: 0.03303970863089544
current error: 0.03302003821996535
current error: 0.03300593577382716
current error: 0.03299582520787167
current error: 0.03298857656866837
Training completed: 782 Iterations


In [33]:
print(theta)

[[ 4.76470715e-16]
 [ 1.74721230e-01]
 [ 5.95543549e-01]
 [-3.27577400e-01]]


In [34]:
#using the above meatured coefficients do the prediction and then 
#measure the accuracy
ycap=predict(X,theta)
print(ycap)

[[-0.99839042]
 [-0.41115402]
 [-0.50662827]
 [ 1.04467432]
 [ 1.41203176]
 [-0.54053337]]


In [35]:
#unscaled values to scaled values
chol_prediction_res=ycap*sc+mc
chol_supplied=np.c_[chol]
np.c_[chol_supplied,chol_prediction_res]
#print(chol)
#print(res)

array([[60.        , 56.04638575],
       [62.        , 62.88123894],
       [59.        , 61.77001267],
       [80.        , 79.82564662],
       [85.        , 84.10132524],
       [60.        , 61.37539078]])

In [0]:
def accuracy(y,ycap,closeness):
  de=100-closeness
  d=np.abs((y-ycap)/y)*100
  pcnt=d[d<=de].size
  n=y.size
  return pcnt/n*100

In [37]:
accuracy(Y,ycap,90)

33.33333333333333

In [38]:
#new_patients.txt
'''
"id","name","age","wgt","hgt"
701,xyz,23,56,5.8
702,bbb,25,45,5.5
703,ccc,27,60,5.7
'''
from google.colab import files
uploaded = files.upload()

Saving class43_patients.txt to class43_patients (1).txt


In [39]:
f=open('class43_patients.txt')
h=f.readline()
lines=f.readlines()
print(lines)

['701,xyz,23,56,5.8\n', '702,bbb,25,45,5.5\n', '703,ccc,27,60,5.7']


In [55]:
a=[]
w=[]
h=[]
for line in lines:
  data=line.strip().split(",")
  a.append(float(data[2]))
  w.append(float(data[3]))
  h.append(float(data[-1]))

a=np.array(a)
w=np.array(w)
h=np.array(h)

A = (a-ma)/sa
W = (w-mw)/sw
H = (h-mh)/sh

o=np.ones(len(lines))

P = np.c_[o,A,W,H]

ycap = predict(P,theta)

print(P)
print(ycap)


[[ 1.         -1.43222975 -0.57273026 -0.16951588]
 [ 1.         -0.89514359 -1.26000658 -1.69515876]
 [ 1.         -0.35805744 -0.3228116  -0.6780635 ]]
[[-0.53579719]
 [-0.35149368]
 [-0.03269032]]


In [57]:
res = ycap*sc+mc
print(res)

[[61.43051526]
 [63.57562652]
 [67.28618351]]
