<a href="https://colab.research.google.com/github/Sathyamlai/python/blob/master/NaiveBayes_sk_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import numpy as np
import pandas as pd

In [78]:
# using NaiveBayes classifier
# comments.txt
'''
i luv you,pos
i hate you,neg
i kill you,neg
i luv to kill you,neg
i admire you,pos
'''

'\ni luv you,pos\ni hate you,neg\ni kill you,neg\ni luv to kill you,neg\ni admire you,pos\n'

In [79]:
from google.colab import files
uploaded = files.upload()

Saving class49_comments_a.txt to class49_comments_a.txt


In [86]:
f=open('class49_comments_a.txt')
lines = f.readlines()
print(lines)

['i love you,pos\n', 'i hate you,neg\n', 'i kill you,neg\n', 'i love to kill you,neg\n', 'i admire you,pos']


In [87]:
# first find the unique words
words=[]
sentiment=[]

for line in lines:
  w=line.strip().lower().split(",")
  words += w[0].split()
  
  s=0
  if w[1] == 'pos':
    s=1
  sentiment.append(s)

print(words)
unique = list(set(words))
print(unique)
print(sentiment)

['i', 'love', 'you', 'i', 'hate', 'you', 'i', 'kill', 'you', 'i', 'love', 'to', 'kill', 'you', 'i', 'admire', 'you']
['i', 'hate', 'to', 'you', 'admire', 'love', 'kill']
[1, 0, 0, 0, 1]


In [88]:
#prepare input matrix
X=np.zeros((len(lines),len(unique)))
print(X)
X.shape

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


(5, 7)

In [89]:
print(unique)

['i', 'hate', 'to', 'you', 'admire', 'love', 'kill']


In [90]:
print(lines)

['i love you,pos\n', 'i hate you,neg\n', 'i kill you,neg\n', 'i love to kill you,neg\n', 'i admire you,pos']


In [91]:
c=0
for w in unique:
  r=0
  for ln in lines:

    if w in ln:
      X[r,c]=1
    r+=1
  c+=1

print(X)

[[1. 0. 0. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 1.]
 [1. 0. 1. 1. 0. 1. 1.]
 [1. 0. 0. 1. 1. 0. 0.]]


In [93]:
#preparing the label matrix
Y=sentiment
print(Y)

[1, 0, 0, 0, 1]


In [95]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(X,Y)

ycap = model.predict(X)

print(np.c_[Y,ycap])


[[1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]]


In [98]:
def acc_clf(y,ycap):
  y=np.array(y)
  ycap=np.array(ycap)

  r = y == ycap
  pcnt = r[r == True].size
  n=y.size
  acc=pcnt/n*100
  return acc

In [99]:
res = acc_clf(Y,ycap)
print("Accuracy:", res)

Accuracy: 100.0


In [97]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(Y,ycap)

print("Accuracy :", acc*100)

Accuracy : 100.0
